# Generated by Django 2.1.7 on 2019-02-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190228_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='vacant',
        ),
        migrations.AddField(
            model_name='table',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
