# Generated by Django 2.1.7 on 2019-02-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190228_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserve',
            new_name='customer',
        ),
    ]
