# Generated by Django 2.1.7 on 2019-03-04 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190228_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='spot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='finish_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Finishing Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Starting Time'),
            preserve_default=False,
        ),
    ]
